### PR TITLE
Formatting changes as well as legibility and spacing changes.

### PR DESCRIPTION
**Pull request by KinglyKrab**

### CODE REVIEW

**Comment by KinglyKrab** [comment]
These changes add the Corruption Resist to the display as well as make it 35 pixels wider so servers (like EZ) with huge stats can see them properly.
image

**Comment by KinglyKrab** [comment]
It also changes the way item stats display so it's not just a blob, but separated and very legible.

image

**Comment by maudigan** [comment]
Made some minor tweaks and commited here: https://github.com/maudigan/charbrowser/commit/84c2a1ae5694e94f9415ca37d3ba75151aa7e958

**Comment by maudigan** [comment]
Oh, I removed the stretch on the right side of the character window cause it felt visually imbalanced but that was there to give room for the regen stats. Will think about a way to accomodate larger integers on those stats without having the large void to the right of the inventory space.

**Pull request closed without merging**
